--- 
version: "3.8"
services: 
  app: 
    image: "naoufeldocker/devopsimage:latest"
    depends_on: 
      - mysqldb
    env_file: ./.env
    environment: 
      SPRING_APPLICATION_JSON: '{ 
        "spring.datasource.url" : 
"jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        }'
    stdin_open: true
    tty: true
    volumes: 
      - .m2:/root/.m2
    ports: 
      - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
    restart: on-failure
  mysqldb: 
    env_file: ./.env
    environment: 
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    image: "mysql:5.7"
    ports: 
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    restart: unless-stopped
    volumes: 
      - "db:/var/lib/mysql"
volumes: 
  db: 
